name: Deploy
on:
  push:
    branches:
      - develop

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: hathora-cloud deploy --appId app-fe9b99fd-7727-4532-9dac-92e064baacce --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: HATHORA_APP_ID=app-fe9b99fd-7727-4532-9dac-92e064baacce npm run build
      - run: npm install -g netlify-cli
      - run: netlify deploy --dir dist --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
