name: Deploy
on:
  push:
    branches:
      - develop

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g hathora
      - run: hathora cloud deploy --appName 3d-platformer --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: APP_ID=app-9b4ef721-6405-49d8-9073-dd89389b2646 npm run build
      - run: npm install -g netlify-cli
      - run: netlify deploy --dir dist --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod
